### ISSUE TITLE
Reference to non-existent field 'C1'.

### ISSUE THREAD

**Issue by edwinyi** [homayunafra/Fuzzy-Least-Squares-Twin-Support-Vector-Machine#1]
Hello, 

I downloaded the code and run the script "main.m". I have the error message in the following:

Reference to non-existent field 'C1'.

Error in test_classification (line 6)
	c1 = classifier_struct.C1;

Error in call_classifier (line 18)
			[resultClass] = 1 + test_classification(classifer_struct, testdata);

Error in main (line 55)
classifier_output = call_classifier(memberships', dataSet, classes, 'lstsvm', cnew, sigmanew);

**Comment by homayunafra** [comment]
This is now solved.
